name: Healthtrack CI Workflow
description: CI workflow for Healthtrack project with Maven, JUnit, JaCoCo, Selenium, JMeter and SonarQube Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-
      
    - name: Run Unit Tests
      run: mvn clean test -Dgroups=unit
    
    - name: Upload Unit Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: junit-reports
        path: target/surefire-reports/
      
    - name: Run Spring Boot in background and store PID
      run: |
        nohup mvn spring-boot:run > app.log 2>&1 &
        echo $! > app.pid
        sleep 10

    - name: Run Selenium Tests
      run: mvn clean test -Dgroups=automation

    - name: Run Code Coverage Analysis
      run: mvn clean test jacoco:report

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/

    - name: Cache JMeter
      id: cache-jmeter
      uses: actions/cache@v4
      with:
        path: apache-jmeter-5.6.3
        key: jmeter-${{ runner.os }}-5.6.3

    - name: Download and Setup JMeter
      if: steps.cache-jmeter.outputs.cache-hit != 'true'
      run: |
        JMETER_VERSION="5.6.3"
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
        tar -xzf apache-jmeter-${JMETER_VERSION}.tgz
        echo "$PWD/apache-jmeter-${JMETER_VERSION}/bin" >> $GITHUB_PATH

    - name: Run JMeter Performance Tests
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/target/jmeter-results
        jmeter -n -t src/test/java/com/weight/healthtrack/performance/performance.jmx \
          -l ${GITHUB_WORKSPACE}/target/jmeter-results/results.jtl \
          -e -o ${GITHUB_WORKSPACE}/target/jmeter-results/dashboard

    - name: Upload JMeter Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: target/jmeter-results/
      
    - name: Stop Spring Boot App
      run: |
        kill $(cat app.pid)
    
    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: SonarQube Scan
      run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

    - name: Upload SonarQube Metadata report
      uses: actions/upload-artifact@v4
      with:
        name: sonarqube-report
        path: target/sonar/report-task.txt
