name: Healthtrack CI Workflow
description: CI workflow for Healthtrack project with Maven, JUnit, JaCoCo, Selenium and JMeter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-

      
    - name: Run Unit Tests
      run: mvn clean test -Dgroups=unit
      
    - name: Run Spring Boot in background and store PID
      run: |
        nohup mvn spring-boot:run > app.log 2>&1 &
        echo $! > app.pid
        sleep 15

    - name: Run Selenium Tests
      run: mvn clean test -Dgroups=automation

    - name: Download and Setup Latest JMeter
      run: |
        JMETER_VERSION="5.6.3"
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
        tar -xzf apache-jmeter-${JMETER_VERSION}.tgz
        export JMETER_HOME=$PWD/apache-jmeter-${JMETER_VERSION}
        echo "$JMETER_HOME/bin" >> $GITHUB_PATH

    - name: Run JMeter Performance Tests
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/target/jmeter-results
        jmeter -n -t src/test/java/com/weight/healthtrack/performance/performance.jmx \
          -l ${GITHUB_WORKSPACE}/target/jmeter-results/results.jtl \
          -e -o ${GITHUB_WORKSPACE}/target/jmeter-results/dashboard

    - name: Analyze JMeter Results
      run: |
        DASHBOARD_DIR=${GITHUB_WORKSPACE}/target/jmeter-results/dashboard
        STATS_FILE="${DASHBOARD_DIR}/statistics.json"

        AVG_RESPONSE_TIME=$(grep -oP 'aggregate_report\.avg=[0-9]+' "$STATS_FILE" | cut -d= -f2)
        ERROR_RATE=$(grep -oP 'aggregate_report\.errorPct=[0-9.]+' "$STATS_FILE" | cut -d= -f2)

        echo "Average Response Time: ${AVG_RESPONSE_TIME}ms"
        echo "Error Rate: ${ERROR_RATE}%"

    - name: Upload JMeter Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: target/jmeter-results/
      
    - name: Stop Spring Boot App
      run: |
        kill $(cat app.pid)

    # - name: SonarQube Scan
    #   run: mvn sonar:sonar
    #   env:
    #     #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
    #     SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

    # - name: Verify Code Coverage
    #   run: |
    #     # Coverage verification
    #     COVERAGE=$(grep -oP 'percentage="\K[^"]+' target/site/jacoco/jacoco.xml | head -1)
    #     echo "Code coverage is: $COVERAGE%"